/**
 * TypeScript port of the config-dependent grading math in
 * pipeline/src/pcpartscan/grade.py.
 *
 * The floor and ceiling of a lot are model outputs and do not change with
 * the user's assumptions; everything downstream of them does. This module
 * re-derives that downstream part (expected revenue, max bid, headroom,
 * ROI, grade) so the workbench can regrade lots in the browser as the
 * assumption sliders move — with zero server round trips.
 *
 * Parity with the Python grader is enforced by test/parity.test.ts against
 * a golden fixture generated by pipeline/tools/make_valuation_golden.py.
 * If you change the math here, change grade.py identically and regenerate
 * the fixture — CI fails on any divergence.
 */

export interface Config {
  buyer_premium: number;
  sales_tax: number;
  pickup_cost: number;
  per_unit_handling: number;
  /**
   * Handling for a lot of parts rather than machines. Testing, wiping and
   * photographing a PC is not the same work as dropping a charger in a box,
   * and one rate for both is a defect rather than caution: at $3 a unit
   * handling came to 121% of expected revenue on the median charger pallet,
   * and every one in the backtest corpus got a max bid of zero however
   * cheap it was. Defaults to $0 — sorting parts costs this operator
   * nothing — so a part lot is priced on what it holds, not on assumed
   * labour. Raise it if sorting ever does cost something.
   */
  part_handling: number;
  recovery: number;
  dead_rate: number;
  target_roi: number;
}

export const DEFAULT_CONFIG: Config = {
  buyer_premium: 0.0,
  sales_tax: 0.0,
  pickup_cost: 0.0,
  per_unit_handling: 3.0,
  part_handling: 0.0,
  recovery: 0.55,
  dead_rate: 0.1,
  target_roi: 0.6,
};

export const CONFIDENCE_GATE = 0.5;

/**
 * The grade of a lot we refuse to price (grade.py UNRATED).
 *
 * When fewer than half a lot's units have an identified component, the
 * ceiling is driven by how many things are on the pallet rather than by
 * what they are, so every number downstream of it is arithmetic we do not
 * stand behind. "U" sorts after "F", which keeps abstentions out of every
 * "grade at least" filter and at the bottom of the default ranking.
 */
export const UNRATED = "U";

export type Grade = "A" | "B" | "C" | "D" | "F" | "U";

/**
 * This config with the handling rate that applies to `family`
 * (grade.py Config.for_family). Answering the family question once, here,
 * leaves every formula below untouched.
 */
export function forFamily(cfg: Config, family?: string | null): Config {
  const part = cfg.part_handling ?? cfg.per_unit_handling;
  if (family !== "part" || part === cfg.per_unit_handling) return cfg;
  return { ...cfg, per_unit_handling: part };
}

/** All-in cost of winning a lot at `hammer` (grade.py Config.all_in). */
export function allIn(cfg: Config, hammer: number, units: number): number {
  return (
    hammer * (1 + cfg.buyer_premium) * (1 + cfg.sales_tax) +
    cfg.pickup_cost +
    cfg.per_unit_handling * units
  );
}

/** Highest hammer price meeting target ROI (grade.py Config.max_hammer). */
export function maxHammer(
  cfg: Config,
  expectedRevenue: number,
  units: number,
): number {
  let budget = expectedRevenue / (1 + cfg.target_roi);
  budget -= cfg.pickup_cost + cfg.per_unit_handling * units;
  const denom = (1 + cfg.buyer_premium) * (1 + cfg.sales_tax);
  return Math.max(0, budget / denom);
}

/** Headroom-based grade, discounted and gated by confidence (grade.py _grade). */
export function gradeFrom(
  relHeadroom: number,
  confidence: number,
  contentsKnown = true,
): Grade {
  if (!contentsKnown) return UNRATED;
  const s = relHeadroom * (0.5 + 0.5 * confidence);
  let g: Grade;
  if (s >= 0.6) g = "A";
  else if (s >= 0.35) g = "B";
  else if (s >= 0.15) g = "C";
  else if (s >= 0.0) g = "D";
  else g = "F";
  if (confidence < CONFIDENCE_GATE && (g === "A" || g === "B")) return "C";
  return g;
}

/** The model-derived facts about a lot that assumptions cannot change. */
export interface LotFacts {
  units: number;
  current_bid: number;
  floor: number;
  /**
   * Whether the bulk-discount fit behind `floor` is sound enough to
   * underwrite against. When false the floor is still shown, but revenue
   * comes from the parts-out estimate alone — a weak fit reading high
   * would inflate max bid on exactly the biggest lots. Absent means
   * trusted (snapshots written before the gate existed).
   */
  floor_trusted?: boolean;
  ceiling: number;
  confidence: number;
  /**
   * Whether enough of the lot's units have an identified component to price
   * it at all. False makes the lot UNRATED: the numbers are still computed
   * so the lot page can show what a generic estimate would have said, but
   * the UI must not present them as a bid ceiling. Absent means known
   * (snapshots written before abstention existed).
   */
  contents_known?: boolean;
  /** "computer" or "part" -- decides which handling rate applies */
  item_family?: "computer" | "part" | null;
}

export interface Regrade {
  expected_revenue: number;
  max_bid: number;
  headroom: number;
  roi_at_current: number;
  grade: Grade;
  /** handling rate actually applied, after the family split */
  handling_applied: number;
  /** per-unit handling at which max bid would reach zero */
  handling_breakeven: number;
}

/** Re-derive every config-dependent number for one lot. */
export function regrade(lot: LotFacts, base: Config = DEFAULT_CONFIG): Regrade {
  const cfg = forFamily(base, lot.item_family);
  const partsOut = lot.ceiling * (1 - cfg.dead_rate) * cfg.recovery;
  const revenue =
    lot.floor_trusted === false ? partsOut : Math.max(partsOut, lot.floor);
  const max_bid = maxHammer(cfg, revenue, lot.units);
  const headroom = max_bid - lot.current_bid;
  const costNow = allIn(cfg, lot.current_bid, lot.units);
  const roi_at_current = costNow > 0 ? (revenue - costNow) / costNow : 0.0;
  const rel = max_bid > 0 ? headroom / max_bid : -1.0;
  const budget = revenue / (1 + cfg.target_roi) - cfg.pickup_cost;
  return {
    expected_revenue: revenue,
    max_bid,
    headroom,
    roi_at_current,
    grade: gradeFrom(rel, lot.confidence, lot.contents_known !== false),
    handling_applied: cfg.per_unit_handling,
    handling_breakeven: lot.units > 0 ? Math.max(0, budget / lot.units) : 0,
  };
}

/**
 * Confidence-weighted headroom, ascending — the board's default order and
 * the pipeline's (grade.py scan). Negated so a plain ascending sort puts
 * the most attractive lot first: a large headroom we do not believe should
 * not outrank a smaller one we do. Abstentions have no number to rank on,
 * so they sink to the bottom whatever their arithmetic says.
 */
export function rankKey(v: Regrade, confidence: number): number {
  if (v.grade === UNRATED) return Infinity;
  return -(v.headroom * confidence);
}
